In [4]:
import numpy as np

In [11]:
L = np.full((10, 10), 0)
for i in range(10):
    for j in range(10):
        if i % 9 == 0 or j % 9 == 0: L[i][j] = 1
L

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
L = np.full((8,8),0)
for i in range(8):
    for j in range(8):
        L[i][j] = (i+j)%2
L

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [14]:
L = np.full((5,5), 0)
for i in range(1, 5):
    L[i][i-1] = i
L

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [15]:
L = np.random.random((5,5))
summa = np.sum(L, axis = 1)
for i in range(5):
    L[i, :] /= summa[i]
L, np.sum(L, axis = 1)

(array([[0.00689562, 0.27580304, 0.0797412 , 0.55082633, 0.08673381],
        [0.29429007, 0.07190345, 0.40796595, 0.10989274, 0.11594779],
        [0.03144219, 0.37935591, 0.10190784, 0.35465499, 0.13263908],
        [0.33141833, 0.40220723, 0.17097568, 0.03832031, 0.05707844],
        [0.1226017 , 0.25095671, 0.22862773, 0.21024764, 0.18756622]]),
 array([1., 1., 1., 1., 1.]))

In [43]:
N = []
L = np.random.random((10, 3))
M = np.min(abs(L-0.5), axis = 1)
for i in range(10):
    for j in range(3):
        if abs(L[i][j]-0.5) == M[i]:
            N.append(L[i][j])
N

[0.2574855216484868,
 0.5305800991898777,
 0.4564847243112389,
 0.3334769639824371,
 0.3424265489354881,
 0.49799730497784067,
 0.4333379453260221,
 0.44492575643205223,
 0.4303091606638879,
 0.5308858869326135]

In [52]:
L = np.random.random((6,6))
M = np.sum(L, axis=1)
N = np.max(L, axis=0)
M/N

array([1.82913346, 2.71448336, 7.0624011 , 3.16325322, 3.07203404,
       4.96814702])

In [55]:
L = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
M = []
for i in range(8):
    if L[i]==0:
        M.append(L[i+1])
np.max(M)

5

In [58]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(8):
    x[i[j]] += 1
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])