In [1]:
import numpy as np

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.
(было без цикла, поэтому без исправлений)

In [2]:
import numpy as np
A = np.ones((10, 10))
A[1:-1, 1:-1] = 0
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.
(было без цикла, поэтому без исправлений)

In [3]:
A = np.ones([8,8])
A[1::2, ::2] = 0
A[::2, 1::2] = 0
A

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю(еще ниже код над диагональю). Остальные значения - нули. 

In [4]:
A = np.diag(np.arange(1, 5), k = -1)
A

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [11]:
A = np.random.random((5,5))
B = A - np.mean(A, axis =1, keepdims = True) # keepdims для корректного вычитания
B

array([[-0.20963095,  0.06686267, -0.25068466,  0.02745148,  0.36600146],
       [ 0.09618635,  0.10641876,  0.38975778, -0.35734896, -0.23501393],
       [ 0.00531562, -0.09885923, -0.02263528, -0.02278008,  0.13895897],
       [-0.26889071,  0.21635382,  0.02233843, -0.15477322,  0.18497169],
       [ 0.23244723,  0.00960044, -0.34712439,  0.19489055, -0.08981383]])

5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.(исправлено)

In [16]:
A = np.random.random((10,3))
length = A.shape[0]
[A[i, np.argmin(abs(A - 0.5), axis = 1)[i]] for i in range(length)]

[0.47123375139775225,
 0.7273690335755143,
 0.37668709676479817,
 0.8408015371223471,
 0.4945849121326866,
 0.4638998213876786,
 0.6444560940136739,
 0.5813919125473108,
 0.3973975658690402,
 0.3417550573819397]

6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [17]:
A = np.random.random((6, 6))
np.sum(A, axis = 1)/ np.max(A, axis = 0)

array([4.18085234, 3.18435584, 3.25819082, 5.71506118, 3.63885838,
       3.81537848])

7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.(как было)

In [18]:
A = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
length = A.shape[0]
max((A[i] for i in range(1, length) if A[i - 1] == 0))

5

8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [19]:
A = np.ones(10)
length = A.shape[0]
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
A += np.bincount(i, minlength = length)
A

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

9. Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.

In [ ]:
first = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
second = np.array([(b[0, 0] + b[0, 1] + b[1, 0] + b[1, 1]) / 4 for t in np.lib.stride_tricks.sliding_window_view(, (2, 2) ) for b in t]).reshape(len(T[0: , 0]) - 1, len(T[0, 0:]) - 1)
print(D)